name: elon_ffi
description: "A new Dart FFI package project."
version: 0.0.6
homepage:

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: 3.29.2

dependencies:
  logging: ^1.3.0
  path: ^1.9.1
  native_assets_cli: ^0.12.0
  # native_toolchain_c: ^0.9.0

dev_dependencies:
  ffi: ^2.1.3
  ffigen: ^13.0.0
  flutter_lints: ^5.0.0
  test: ^1.25.8
